adas/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from adas import views as adasViews
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('inicio/', views.inicio, name='inicio'),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('servicios/', views.servicios, name='servicios'),

    path('administrador/', include('administrador.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('autenticacion/', include('django.contrib.auth.urls')),
    path('', adasViews.home, name='home'),
    

]

# Para servir archivos media en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Configure Admin Titles
admin.site.site_header = "Página administradora de ADAS"
admin.site.site_title = "Titulo de la página administradora"
admin.site.index_title = "Bienvenido al area de administración..."

administrador/urls.py
from django.urls import path
from . import views
from clustering import views as clusteringViews

urlpatterns = [
    path('panel/', views.panel, name='panel'),  
    path('estadisticas/', views.estadisticas, name='estadisticas'), 
    
    # Gemini 
    path('creative/generar-message/', views.generar_message_ia, name='generar_message_ia'),
    path('creative/generar-body/', views.generar_body_ia, name='generar_body_ia'),
    path('buscar_vacante/', views.buscar_vacante, name='buscar_vacante'),

    path('set_plataforma/', views.set_plataforma, name='set_plataforma'),

    # Post X
    path('crear_post/', views.crear_post, name='crear_post'),
    # Campaña
    path('campaña/', views.campaña, name='campaña'),
    path('crear_campaña/', views.crear_campaña, name='crear_campaña'),
    path('mis_campañas/', views.mis_campañas, name='mis_campañas'),
    # AdSet
    path('obtener_optimization_goals/', views.obtener_optimization_goals, name='obtener_optimization_goals'),
    path('ad_set/', views.ad_set, name='ad_set'),
    path('crear_adset/', views.crear_adset, name='crear_adset'),
    path('mis_adsets/', views.mis_adsets, name='mis_adsets'),
    # Ad
    path('ad/', views.ad, name='ad'),
    path('crear_ad/', views.crear_ad, name='crear_ad'),
    path('mis_ads/', views.mis_ads, name='mis_ads'),
    #Creative
    path('crear_creative/', views.crear_creative, name='crear_creative'),
    path('mis_creatives/', views.mis_creatives, name='mis_creatives'),
    # Administración de contenido (ads y posts)
    path("revisar/<str:tipo>/pendientes/", views.revisar_contenido_pendiente, name="revisar_contenido_pendiente"),
    path("aprobar/<str:tipo>/<str:objeto_id>/", views.aprobar_contenido, name="actualizar_estado_contenido"),
    path("mis-solicitudes/<str:tipo>/", views.mis_solicitudes_contenido, name="mis_solicitudes_contenido"),

    # Vacantes
    path('vacantes/', views.mis_vacantes, name='vacantes'),

    # ---------------------- VER MIS VACANTES ----------------------#
    #path('vacantes/', views.mis_vacantes, name='mis_vacantes'),
    path('cargar_excel/', views.cargar_excel, name='cargar_excel'),

    # ---------------------- POSTS EN TIKTOK ----------------------#
    path('crear_post_tiktok/', views.crear_post_tiktok, name='crear_post_tiktok'),
    path('mis_solicitudes_contenido/post_tiktok/', views.mis_solicitudes_post_tiktok, name='mis_solicitudes_contenido_post_tiktok'),
    path('revisar_contenido_pendiente/post_tiktok/', views.revisar_contenido_pendiente_post_tiktok, name='revisar_contenido_pendiente_post_tiktok'),

    path('tiktok/advertisers/', views.advertiser_tiktok_list, name='advertiser_tiktok_list'),
    path('tiktok/advertisers/create/', views.advertiser_tiktok_create, name='advertiser_tiktok_create'),
    path('tiktok/advertisers/<int:advertiser_id>/campaigns/', views.campaign_tiktok_list, name='campaign_tiktok_list'),
    path('tiktok/advertisers/<int:advertiser_id>/campaigns/create/', views.campaign_tiktok_create, name='campaign_tiktok_create'),
    path('tiktok/campaigns/<int:campaign_id>/adgroups/', views.adgroup_tiktok_list, name='adgroup_tiktok_list'),
    path('tiktok/campaigns/<int:campaign_id>/adgroups/create/', views.adgroup_tiktok_create, name='adgroup_tiktok_create'),
    path('tiktok/adgroups/<int:adgroup_id>/ads/', views.ad_tiktok_list, name='ad_tiktok_list'),
    path('tiktok/adgroups/<int:adgroup_id>/ads/create/', views.ad_tiktok_create, name='ad_tiktok_create'),
    path('tiktok/adgroups/', views.adgroup_tiktok_all, name='adgroup_tiktok_all'),
    path('tiktok/ads/', views.ad_tiktok_all, name='ad_tiktok_all'),
    path('tiktok/adgroups/create/', views.adgroup_tiktok_create_select_campaign, name='adgroup_tiktok_create_select_campaign'),
    path('tiktok/ads/create/', views.ad_tiktok_create_select_adgroup, name='ad_tiktok_create_select_adgroup'),

    # Listar todos los Ads publicados (público)
    path('tiktok/ads/', views.ads_tiktok_publicados, name='ads_tiktok_publicados'),

    # Listar Ads pendientes para revisión (solo admin/staff)
    path('tiktok/ads/pendientes/', views.revisar_ads_tiktok, name='revisar_ads_tiktok'),

    # Aprobar o rechazar un Ad (solo admin/staff)
    path('tiktok/ads/aprobar/<int:ad_id>/', views.aprobar_rechazar_ad_tiktok, name='aprobar_rechazar_ad_tiktok'),

    # Ver mis solicitudes de Ads (usuario)
    path('tiktok/ads/mis-solicitudes/', views.mis_solicitudes_ads_tiktok, name='mis_solicitudes_ads_tiktok'),



    # AUTORELLENO VACANTES A POST X 
    path('obtener-vacante/<int:vacante_id>/', views.obtener_vacante, name='obtener_vacante'),
    


    #Clustering
    path('mis_modelos/', clusteringViews.ver_modelos_entrenados, name='mis_modelos'),
    path('entrenar_modelo/', clusteringViews.entrenar_modelo, name='entrenar_modelo'),
    path('mis_clusters/', clusteringViews.ver_clusters, name='mis_clusters'),
    path('mis_targeting/', clusteringViews.mis_targeting, name='mis_targeting'),
    path('clusters/<int:modelo_id>/<int:cluster>/targeting/', clusteringViews.definir_targeting, name='definir_targeting'),
    path('clusters/<int:modelo_id>/<int:cluster>/targeting/generar_ia/', clusteringViews.generar_targeting_ia, name='generar_targeting_ia'),


]

administrador/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from clustering.models import ModeloEntrenado, ClusterTargeting

# ---------------------- TABLA PARA REVISIÓN DE ADMINISTRADOR----------------------#
class Revision(models.Model):
    ESTADOS = [
        ('PENDIENTE', 'Pendiente'),
        ('APROBADO', 'Aprobado'),
        ('RECHAZADO', 'Rechazado'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='revisiones')
    estado = models.CharField(max_length=20, choices=ESTADOS, default='Pendiente')
    comentario_admin = models.TextField(blank=True, null=True, help_text="Comentario del administrador al aprobar o rechazar")
    created_at = models.DateField(default=date.today)

    def __str__(self):
        return f"Revisión por {self.usuario} - {self.estado}"
    
# ---------------------- MODELOS X ----------------------#
class Post(models.Model):
    
    nombre = models.CharField(max_length=250)
    texto = models.TextField(blank=True, null=True)  # Texto del anuncio
    revision = models.OneToOneField(Revision, on_delete=models.CASCADE, null=True, blank=True) # Campo para aprovación
    created_at = models.DateField(default=date.today)
    #post_id = models.CharField(max_length=250)

    def __str__(self):
        return self.texto

# ---------------------- MODELOS META ----------------------#
class Campaign(models.Model):
    # Keys
    campaign_id = models.CharField(max_length=255, blank=True, default="") 
    
    OBJECTIVES = [
        ('CONVERSIONS', 'Conversiones'),
        ('POST_ENGAGEMENT', 'Interacción'),
        ('BRAND_AWARENESS', 'Conocimiento de marca'),
        ('LEAD_GENERATION', 'Leads'),
    ]

    PLATAFORMAS = [
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    ]

    plataforma = models.CharField(max_length=50, choices=PLATAFORMAS, default="facebook")
    nombre = models.CharField(max_length=255)
    objective = models.CharField(max_length=250, choices=OBJECTIVES, default="REACH") 

    #Adicionales (no están en el formulario)
    created_at = models.DateField(default=date.today)

    def __str__(self):
        return self.nombre
    

class AdSet(models.Model):
    # Keys 
    adset_id= models.CharField(blank=True, max_length=100) 
    campaign_id = models.ForeignKey(Campaign, on_delete=models.CASCADE) # FK
    targeting = models.ForeignKey(ClusterTargeting, null=True, blank=True, on_delete=models.SET_NULL)

    #añadir campo targeting
    BILLING_EVENTS = [
        ('IMPRESSIONS', 'CPM (Por cada 1000 impresiones)'),
        ('CLICKS', 'CPC (Por cada click)'),
        ('LINK_CLICKS', 'Clicks en enlaces específicos'),
        ('POST_ENGAGEMENT', 'Interacciones'),
        ('VIDEO_VIEWS', 'Vistas de video'),
    ]
    OPTIMIZATION_GOALS = [
        ('IMPRESSIONS', 'Conversiones'),
        ('REACH', 'Alcance'),
        ('POST_ENGAGEMENT', 'Engagement con el post'),
        ('VIDEO_VIEWS', 'Vistas'),
        ('IMPRESSIONS', 'Impresiones'),
        ('LEAD_GENERATION', 'Leads'),
        ('CONVERSIONS', 'Conversiones'),
        ('VALUE', 'Value'),
        ('LANDING_PAGE_VIEWS', 'Landing page'),
    ]

    PLATAFORMAS = [
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    ]

    plataforma = models.CharField(max_length=50, choices=PLATAFORMAS, default="facebook")
    nombre = models.CharField(max_length=255)
    daily_budget = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    billing_event = models.CharField(max_length=250, choices=BILLING_EVENTS, blank=True, default="REACH") 
    optimization_goal = models.CharField(max_length=250, choices=OPTIMIZATION_GOALS, blank=True, default="REACH")  
    status = models.CharField(max_length=255, blank=True)
    
    #Adicionales (no están en el formulario
    created_at = models.DateField(default=date.today)

    def __str__(self):
        return self.nombre

class Creative(models.Model):
    # Keys
    creative_id = models.CharField(max_length=100, blank=True) 

    PLATAFORMAS = [
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    ]

    plataforma = models.CharField(max_length=50, choices=PLATAFORMAS, default="facebook")
    nombre = models.CharField(max_length=255) # Nombre interno para identificación en la API
    name = models.CharField(max_length=255) # Título visible en el anuncio
    message = models.TextField(blank=True, null=True)  # Capta la atención inicial, PRINCIPAL
    body = models.TextField(blank=True, null=True)  # Da un poco mas de contexto 
    image_url = models.URLField(blank=True, null=True)  # Imagen del anuncio
    link = models.URLField(blank=True, null=True)  # URL del enlace al que redirige el anuncio
    call_to_action = models.CharField(max_length=50, choices=[
        ("LEARN_MORE", "Más información"),
        ("SIGN_UP", "Registrarse"),
        ("SHOP_NOW", "Comprar ahora"),
        ("CONTACT_US", "Contáctanos"),
        ("SUBSCRIBE", "Suscribirse"),
        ("GET_OFFER", "Obtener oferta"),
    ])

    #Adicionales (no están en el formulario)
    created_at = models.DateField(default=date.today)

    def __str__(self):
        return self.nombre
    

class Ad(models.Model):
    #Keys
    ad_id= models.CharField(blank=True, max_length=100) 
    adset_id = models.ForeignKey(AdSet, on_delete=models.CASCADE) # FK
    creative_id = models.ForeignKey(Creative, on_delete=models.CASCADE) # FK

    ESTADOS = [
        ('PENDIENTE', 'Pendiente'),
        ('APROBADO', 'Aprobado'),
        ('RECHAZADO', 'Rechazado'),
    ]
    
    PLATAFORMAS = [
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    ]

    plataforma = models.CharField(max_length=50, choices=PLATAFORMAS, default="facebook")
    nombre = models.CharField(max_length=250)
    status = models.CharField(max_length=100, blank=True)
    revision = models.OneToOneField(Revision, on_delete=models.CASCADE, null=True, blank=True) # Campo para aprovación
    created_at = models.DateField(default=date.today)

    def __str__(self):
        return self.nombre
    
# ---------------------- VACANTES ----------------------#
class Vacante(models.Model):
    INDUSTRIAS = [
        ('TECNOLOGIA', 'Tecnología e Informática'),
        ('SALUD', 'Salud y Medicina'),
        ('EDUCACION', 'Educación'),
        ('INGENIERIA', 'Ingeniería y Manufactura'),
        ('VENTAS', 'Ventas y Marketing'),
        ('ADMINISTRACION', 'Administración y Negocios'),
        ('LEGAL', 'Legal'),
        ('LOGISTICA', 'Logística y Transporte'),
        ('SERVICIOS', 'Servicios Generales'),
        ('TURISMO', 'Turismo y Hospitalidad'),
        ('ENTRETENIMIENTO', 'Artes, Medios y Entretenimiento'),
        ('INVESTIGACION', 'Ciencia e Investigación'),
        ('AGROINDUSTRIA', 'Agroindustria y Medio Ambiente'),
    ]

    vacante = models.CharField(max_length=255)
    empresa = models.TextField(max_length=100)
    ubicacion = models.CharField(max_length=255)
    contrato = models.CharField(max_length=100)
    salario = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    industria = models.CharField(max_length=100, choices=INDUSTRIAS, null=True)
    modalidad = models.CharField(max_length=50, choices=[('Remoto', 'Remoto'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], null=True)
    experiencia = models.CharField(max_length=100, null=True)
    grupo = models.IntegerField(null=True, blank=True) # Para clustering
    modelo_clustering = models.ForeignKey(ModeloEntrenado, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):  
        return self.vacante
    
# ---------------------- MODELOS TIKTOK ---------------------- #
class AdvertiserTikTok(models.Model):
    nombre = models.CharField(max_length=100)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return self.nombre

class CampaignTikTok(models.Model):
    advertiser = models.ForeignKey(AdvertiserTikTok, on_delete=models.CASCADE, related_name='campaigns')
    nombre = models.CharField(max_length=100)
    objetivo = models.CharField(max_length=100)
    presupuesto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nombre

class AdGroupTikTok(models.Model):
    campaign = models.ForeignKey(CampaignTikTok, on_delete=models.CASCADE, related_name='adgroups')
    nombre = models.CharField(max_length=100)
    segmentacion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class AdTikTok(models.Model):
    adgroup = models.ForeignKey(AdGroupTikTok, on_delete=models.CASCADE, related_name='ads')
    nombre = models.CharField(max_length=100)
    contenido = models.TextField()
    url = models.URLField(blank=True)
    imagen = models.ImageField(upload_to='tiktok_ads_images/', null=True, blank=True)
    # ...otros campos...

    ESTADOS = [
        ('PENDIENTE', 'Pendiente'),
        ('APROBADO', 'Aprobado'),
        ('RECHAZADO', 'Rechazado'),
        ('PUBLICADO', 'Publicado'),
    ]
    
    status = models.CharField(max_length=100, blank=True)
    estado = models.CharField(max_length=20, choices=ESTADOS, default='PENDIENTE')
    comentario_admin = models.TextField(blank=True, null=True)

    revision = models.OneToOneField(Revision, on_delete=models.CASCADE, null=True, blank=True) # Campo para aprovación
    created_at = models.DateField(default=date.today)

    def __str__(self):
        return self.nombre
    

administrador/templates/ad.html
{% extends 'panel.html' %}

{% block content %}
<h2>Aquí se podrán definir las métricas de los ads</h2>

<style>
    .form-group {
        margin-bottom: 15px;
        display: flex;
        flex-direction: column;
    }

    .form-help {
        font-size: 0.9em;
        color: #6c757d;
        margin-top: 3px;
    }

    .card-container {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        height: 100vh;  
        margin-top: 50px; 
    }

    .card-custom {
        width: 900px;  
        padding: 20px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
        border-radius: 10px; 
    }

    @keyframes fadeOut {
        0% { opacity: 1; }
        90% { opacity: 1; }
        100% { opacity: 0; display: none; }
    }
    
    .btn-primary {
        background-color: #3dc971; /* Color de fondo */
        border: none; /* Sin borde */
        color: white; /* Color del texto */
        
        cursor: pointer; /* Cambiar el cursor al pasar el mouse */
        font-weight: bold; /* Texto en negrita */
        transition: background-color 0.3s ease; /* Animación al pasar el mouse */
    }

    .btn-primary:hover {
        background-color: #9ee4b8; /* Cambiar el color al pasar el mouse */
    }

    .alert {
        animation: fadeOut 6s ease-in-out forwards;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="form-container">
    <div class="card-container">
        <div class="card card-custom">
            {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <li><strong>{{ field|title }}:</strong> {{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            {% if messages %}
                {% for message in messages %}
                    <div class="alert 
                        {% if message.tags == 'success' %}alert-success
                        {% elif message.tags == 'error' %}alert-danger{% endif %} 
                        alert-dismissible fade show" role="alert">
                        
                        {{ message }}

                        {% if message.tags == 'success' %}
                            <a href="{% url 'mis_ads' %}" class="btn btn-primary btn-sm">Ver ads creados</a>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endif %}

            <h2 style="text-align:center;">Crear Ad</h2>

            <form method="POST" action="{% url 'crear_ad' %}">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_nombre">Nombre del ad</label>
                    {{ form.nombre }}
                    <span class="form-help">Asigna un nombre identificador para este anuncio.</span>
                </div>

                <div class="form-group">
                    <label for="id_adset_id">Adset ID</label>
                    {{ form.adset_id }}
                    <span class="form-help">Selecciona el nombre del ad set al que pertenece este anuncio.</span>
                </div>

                <div class="form-group">
                    <label for="id_adset_id">Adset ID</label>
                    {{ form.adset_id }}
                    <span class="form-help">Ingresa el ID del ad set al que pertenece este anuncio.</span>
                </div>

                <div class="form-group">
                    <label for="id_creative_id">Creative ID</label>
                    {{ form.creative_id }}
                    <span class="form-help">Ingresa el ID del contenido creativo que se usará.</span>
                </div>


                <button type="submit" class="btn btn-primary w-100">Crear Ad</button> 
               {{ form.plataforma }}
            </form>

    
        </div>
    </div>
</div>
<script>
    //Script para guardar la plataforma seleccionada en localStorage
    document.addEventListener('DOMContentLoaded', function () {
        const plataforma = localStorage.getItem('selectedSocial') || 'facebook';
        const input = document.getElementById('plataforma-input');
        if (input) {
            input.value = plataforma;
        }
    });
</script>
{% endblock content %}

administrador/templates/aprobar_ad.html
{% extends 'panel.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Revisión del Anuncio</h2>
    <div class="card p-4 shadow-sm">
        <p><strong>Texto:</strong> {{ ad.texto }}</p>
        <p><strong>Autor:</strong> {{ ad.usuario.username }}</p>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="estado" class="form-label">Cambiar estado</label>
                <select name="estado" id="estado" class="form-select" required>
                    <option value="Aprobado">Aprobar</option>
                    <option value="Rechazado">Rechazar</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="comentario" class="form-label">Comentario</label>
                <textarea name="comentario" id="comentario" class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>
</div>
{% endblock content %}

administrador/templates/aprobar_contenido.html
{% extends 'panel.html' %}

{% block content %}
<style>
    .btn-success {
        background-color: #3dc971; /* Color de fondo */
        border: none; /* Sin borde */
        color: white; /* Color del texto */
        
        cursor: pointer; /* Cambiar el cursor al pasar el mouse */
        font-weight: bold; /* Texto en negrita */
        transition: background-color 0.3s ease; /* Animación al pasar el mouse */
    }

    .btn-success:hover {
        background-color: #9ee4b8; /* Cambiar el color al pasar el mouse */
    }
</style>
<div class="container mt-4">
    <h2 class="mb-4">Revisión de {{ tipo|title }}</h2>
    <div class="card p-4 shadow-sm">
        {% if tipo == 'post' %}
            <h5 class="card-title fw-bold">{{ contenido.texto }}</h5>
        {% endif %}
        {% if tipo == 'ad' %}
            <h5 class="card-title fw-bold">{{ contenido.nombre }}</h5>
        {% endif %}
        <p><strong>Autor:</strong> {{ contenido.revision.usuario.username }}</p>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="estado" class="form-label">Cambiar estado</label>
                <select name="estado" id="estado" class="form-select" required>
                    <option value="Aprobado">Aprobar</option>
                    <option value="Rechazado">Rechazar</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="comentario" class="form-label">Comentario</label>
                <textarea name="comentario" id="comentario" class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-success w-100">Guardar</button>
        </form>
    </div>
</div>
{% endblock content %}

administrador/templates/campaña.html
{% extends 'panel.html' %}

{% block content %}
<h2>Aquí se podrán definir las métricas de las campañas</h2>

<style>
    .form-group {
        margin-bottom: 15px;
        display: flex;
        flex-direction: column;
    }

    .form-help {
        font-size: 0.9em;
        color: #6c757d;
        margin-top: 3px;
    }

    .card-container {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        height: 100vh;  
        margin-top: 50px; 
    }

    .card-custom {
        width: 900px;  
        padding: 20px;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
        border-radius: 10px; 
    }

    @keyframes fadeOut {
        0% { opacity: 1; }
        90% { opacity: 1; }
        100% { opacity: 0; display: none; }
    }
    .btn-primary {
        background-color: #3dc971; /* Color de fondo */
        border: none; /* Sin borde */
        color: white; /* Color del texto */
        
        cursor: pointer; /* Cambiar el cursor al pasar el mouse */
        font-weight: bold; /* Texto en negrita */
        transition: background-color 0.3s ease; /* Animación al pasar el mouse */
    }

    .btn-primary:hover {
        background-color: #9ee4b8; /* Cambiar el color al pasar el mouse */
    }

    .alert {
        animation: fadeOut 6s ease-in-out forwards;
    }
</style>

<div class="form-container">
    <div class="card-container">
        <div class="card card-custom">

            {% if messages %}
                {% for message in messages %}
                    <div class="alert 
                        {% if message.tags == 'success' %}alert-success
                        {% elif message.tags == 'error' %}alert-danger{% endif %} 
                        alert-dismissible fade show" role="alert">
                        
                        {{ message }}

                        {% if message.tags == 'success' %}
                            <a href="{% url 'mis_campañas' %}" class="btn btn-primary btn-sm">Ver campañas creadas</a>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endif %}

            <h2>Crear Campaña</h2>

            <form method="POST" action="{% url 'crear_campaña' %}">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_nombre">Nombre de la campaña</label>
                    {{ form.nombre }}
                    <span class="form-help">Escribe un nombre que te ayude a identificar la campaña fácilmente.</span>
                </div>

                <div class="form-group">
                    <label for="id_objective">Selecciona el objetivo</label>
                    {{ form.objective }}
                    <span class="form-help">Define el objetivo principal de tu campaña.</span>
                </div>
                {{ form.plataforma }}
                <div style="text-align:center;">
                    <button type="submit" class="btn btn-primary w-100">Crear Campaña</button>
                </div>

            </form>
            
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const plataforma = localStorage.getItem('selectedSocial') || 'facebook';
        const input = document.getElementById('plataforma-input');
        if (input) {
            input.value = plataforma;
        }
    });
</script>

{% endblock content %}

administrador/templates/estadisticas.html
{% extends 'panel.html' %}

{% block content %}
<h2>Aquí se podrán visualizar estadísticas de anuncios y vacantes</h2>
{% endblock content %}

administrador/templates/mis_ads.html
{% extends 'panel.html' %} 

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Mis ads</h1>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
        {% for ad in ads %}
        {% if ad.revision.estado == "Aprobado" %}
            <div class="col">
                <div class="card border rounded-3 shadow-sm p-3">
                    <div class="card-body">
                        <h5 class="card-title fw-bold">{{ ad.nombre }}</h5>
                        <p class="card-text"><strong>Id de adset: </strong>{{ ad.adset_id}}</p>
                        <!--
                        {% if adset.campaign_id %}
                        <p class="card-text"><strong>Id: </strong> {{ adset.campaign_id}}</p>
                        {% endif %}
                        -->
                    </div>
                </div>
            </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock content %}